In [1]:
import numpy as np

In [2]:
np.__version__

'1.13.3'

In [3]:
A = list(range(10))

In [21]:
# style used here is list comphrension
B = [str(c) for c in A]
print A
print B
[type(item) for item in A]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


[int, int, int, int, int, int, int, int, int, int]

In [103]:
# creating arrays


# arrays in Numpy has one datatype
#alway specify the datatype to be sure of the data contained in the array
print np.zeros(10)
print np.zeros(10, dtype="int")

# 3 by 5 column matrix
print np.ones((3,5), dtype="string")

# matrix with a predefined value
print np.full((4,4), 'xxx')

# create a array with a set sequence
print np.arange(3, 30, 5)

# array with even space within the range of value - just three values within 0 and 1
print np.linspace(0, 1, 3)

# 3 by 3 matrix with mean 0 and sd 1 with a distribution
print np.random.normal(4,0.55, (3,3))

# identity matrix
print np.eye(4)

print np.random.seed(4)

#creating arrays with different dimension and with random int 
x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(4,5)) #two dimension
x3 = np.random.randint(10, size=(4,4,5)) # three dimension
print x2.ndim
print x2.shape
print x2.size
print x1
print x2
print "---"
print x3



[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[0 0 0 0 0 0 0 0 0 0]
[['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']
 ['1' '1' '1' '1' '1']]
[['xxx' 'xxx' 'xxx' 'xxx']
 ['xxx' 'xxx' 'xxx' 'xxx']
 ['xxx' 'xxx' 'xxx' 'xxx']
 ['xxx' 'xxx' 'xxx' 'xxx']]
[ 3  8 13 18 23 28]
[ 0.   0.5  1. ]
[[ 5.49423648  4.3056347   3.97600924]
 [ 4.67244727  4.02507935  4.75932282]
 [ 4.11839193  4.30264759  3.78919737]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
None
2
(4, 5)
20
[7 5 1 8 7 8]
[[2 9 7 7 7]
 [9 8 4 2 6]
 [4 3 0 7 5]
 [5 9 6 6 8]]
---
[[[2 5 8 1 2]
  [7 0 8 3 1]
  [0 3 2 3 2]
  [9 2 1 0 1]]

 [[9 9 0 7 2]
  [6 3 7 8 2]
  [6 7 7 9 2]
  [7 5 3 0 5]]

 [[4 3 8 9 5]
  [8 6 7 0 4]
  [6 8 4 8 1]
  [9 5 4 2 3]]

 [[4 7 6 6 8]
  [0 3 5 6 1]
  [1 6 0 8 7]
  [5 7 6 8 4]]]


In [113]:
print x2[3,2] # zero base indexing -:- 3rd value of the 4th row
x2[3,-1] = 5
print x2[3,-1]

6
5


In [122]:
j = np.arange(10)
print j
print j[:5]
print j[4:]
print j[2:4]
print j[: : 3]
print j[3::2]
j[::-1] # reverse array

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[4 5 6 7 8 9]
[2 3]
[0 3 6 9]
[3 5 7 9]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [134]:
x = np.array([2,3,4])
y = np.array([7,8,9])
z=[1,5,6]
print np.concatenate([x,y,z])

#use grid to create a 2-dimensional array

grid = np.array([x,y])
print grid
print np.concatenate([grid, grid])
print np.concatenate([grid, grid], axis=1)

[2 3 4 7 8 9 1 5 6]
[[2 3 4]
 [7 8 9]]
[[2 3 4]
 [7 8 9]
 [2 3 4]
 [7 8 9]]
[[2 3 4 2 3 4]
 [7 8 9 7 8 9]]
