In [2]:
import numpy as np
import pandas as pd
import scipy

In [11]:
list1 = [1,2,3,4,5,6]
array1 = np.array(list1) #array modifiy any object into a simpler form

In [12]:
print array1
print list1
print array1.dtype

['1' '2' '3' '4' '5' '6']
[1, 2, 3, 4, 5, '6']
|S21


In [ ]:
#properties of an array
print array1.shape
print array1.reshape(1,6) # takes rows and columns

In [19]:
#arrange - allows you to have an arrangement of numbers works like range
print np.arange(50)
print np.zeros([3,5], dtype="int")
print np.ones([2,3]) #range
print range(0, 20,3)
print list(range(0, 20))
print np.linspace(2,20,10)

#try asarray, and 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[0, 3, 6, 9, 12, 15, 18]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[  2.   4.   6.   8.  10.  12.  14.  16.  18.  20.]


In [ ]:
#pandas gives you afeeling of an excel shit -
#--object type
#one dimensional object - 1 column many rows - --series
#data frame - 2 dimensional - any numbers of row and colums
#panel - 2 dimensional plus sheet to form an object - hence 3, dimension

In [20]:
#creating series - data and index(naming)
data1 = ['bolgota','columbia','north vila'] # can also use a turple and a dictionary
data2 ={1:"one",2:"two"}
series1 =  pd.Series(data1, index=['b','c','n'])
series2 =  pd.Series(data2)
print series1
print series2

TypeError: __init__() got an unexpected keyword argument 'columns'

In [67]:
# properties
print dframe1.head(2)
#try

   0
1  1
2  2


In [23]:
#data frame - group object to have more than one column
data4 = [1,2,3,4,5]
data5 = [[1,2],[2,3]] # can be grouped with turples to
dframe1 = pd.DataFrame(data4, index=[1,2,3,4,5])


print dframe1
print dframe1.loc[3]
#try append

   0
1  1
2  2
3  3
4  4
5  5
0    3
Name: 3, dtype: int64


In [70]:
dir(pd) # reaad csv to read csv files

['Categorical',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'ExcelFile',
 'ExcelWriter',
 'Expr',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int64Index',
 'Interval',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseSeries',
 'Term',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt64Index',
 'WidePanel',
 '_DeprecatedModule',
 '__builtins__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 '__version__',
 '__warningregistry__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p10',
 '_np_version_under1p11',
 '_np_version_under1p12',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_tslib',
 '_version',
 'api',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'datetime',
 'datetools',
 'describe_option',
 'error

In [72]:
file = pd.read_csv('csv file')

TypeError: parser_f() takes at least 1 argument (0 given)

In [ ]:
#assignment - learn to use linear  regression in preprocessing and cross _validation sklearn 

In [ ]:
# write a function that can generate a number index for any data

#previous class- learn lamda, use sql to store baby files